import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeContextProvider from "@/providers/theme-context";
import ThemeSwitch from "@/components/theme-switch";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} `}>
        <SessionProvider>
        <ThemeContextProvider>
          {children}
          <ThemeSwitch />
        </ThemeContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
