import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeContextProvider from "@/providers/theme-context";
import ThemeSwitch from "@/components/theme-switch";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ThemeContextProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <SessionProvider>
            <main className="flex h-full w-full flex-col items-center justify-between p-24">
              {children}
            <ThemeSwitch />
            </main>
          </SessionProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
